/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TopUpRouteImport } from './routes/top-up'
import { Route as LoginMobileRouteImport } from './routes/login_.mobile'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as SignupMobileRouteImport } from './routes/signup_.mobile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TopUpRoute = TopUpRouteImport.update({
  id: '/top-up',
  path: '/top-up',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMobileRoute = LoginMobileRouteImport.update({
  id: '/login_/mobile',
  path: '/login/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupMobileRoute = SignupMobileRouteImport.update({
  id: '/signup_/mobile',
  path: '/signup/mobile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/top-up': typeof TopUpRoute
  '/login/mobile': typeof LoginMobileRoute
  '/product/$slug': typeof ProductSlugRoute
  '/signup/mobile': typeof SignupMobileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/top-up': typeof TopUpRoute
  '/login/mobile': typeof LoginMobileRoute
  '/product/$slug': typeof ProductSlugRoute
  '/signup/mobile': typeof SignupMobileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/top-up': typeof TopUpRoute
  '/login_/mobile': typeof LoginMobileRoute
  '/product/$slug': typeof ProductSlugRoute
  '/signup_/mobile': typeof SignupMobileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/top-up'
    | '/login/mobile'
    | '/product/$slug'
    | '/signup/mobile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/top-up'
    | '/login/mobile'
    | '/product/$slug'
    | '/signup/mobile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/signup'
    | '/top-up'
    | '/login_/mobile'
    | '/product/$slug'
    | '/signup_/mobile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TopUpRoute: typeof TopUpRoute
  LoginMobileRoute: typeof LoginMobileRoute
  ProductSlugRoute: typeof ProductSlugRoute
  SignupMobileRoute: typeof SignupMobileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-up': {
      id: '/top-up'
      path: '/top-up'
      fullPath: '/top-up'
      preLoaderRoute: typeof TopUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/mobile': {
      id: '/login_/mobile'
      path: '/login/mobile'
      fullPath: '/login/mobile'
      preLoaderRoute: typeof LoginMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/mobile': {
      id: '/signup_/mobile'
      path: '/signup/mobile'
      fullPath: '/signup/mobile'
      preLoaderRoute: typeof SignupMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TopUpRoute: TopUpRoute,
  LoginMobileRoute: LoginMobileRoute,
  ProductSlugRoute: ProductSlugRoute,
  SignupMobileRoute: SignupMobileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
